//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cl.cursocsharp.dominio.entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle
    {
        public int IdDetalle { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public Nullable<int> IdArticulo { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<double> Precio { get; set; }
    }
}
